name: whwtimeseries
channels:  
  - conda-forge
dependencies:
  - python=3.7
  - ipython
  - ipykernel
  - requests
  - geopandas
  - geojson
  - ulmo
  - owslib
  - matplotlib
  - seaborn
  - cartopy
  - folium
  - xlrd
