name: whwtimeseries
channels:  
  - conda-forge
dependencies:
  - python=3.6
  - ipython
  - ipykernel
  - requests
  - geopandas
  - geojson
  - ulmo
  - owslib
  - matplotlib
  - seaborn
  - cartopy
  - folium
  - xlrd
  - pip:
    - git+https://github.com/emiliom/ulmo.git@pandas0_24
